<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>net.linlan.stage</groupId>
    <artifactId>stage-rapidocr-server</artifactId>
    <version>1.0.4</version>
    <packaging>jar</packaging>
    <name>stage-rapidocr-server</name>
    <description>RapidOCR的验证和服务工程，通过模型的调用，完成多平台适配</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <maven.version>3.1.0</maven.version>
        <maven.compile.version>3.7.0</maven.compile.version>
        <maven.source.version>3.3.1</maven.source.version>
        <maven.javadoc.version>3.5.0</maven.javadoc.version>
        <maven.pluging.version>3.8.3</maven.pluging.version>
        <maven.pluging.annotations.version>3.6.1</maven.pluging.annotations.version>
        <maven.tree.version>3.1.0</maven.tree.version>
        <maven.gpg.version>3.1.0</maven.gpg.version>
        <maven.sonatype.version>0.7.0</maven.sonatype.version>
        <spring.boot.version>2.7.18</spring.boot.version>
        <spring-framework.version>5.3.31</spring-framework.version>
        <spring-security.version>5.7.10</spring-security.version>
        <lombok.version>1.18.30</lombok.version>

        <linlan.tools.version>2.6.6</linlan.tools.version>

        <model.version.112>1.1.2</model.version.112>
        <model.version.120>1.2.0</model.version.120>
        <model.version.122>1.2.2</model.version.122>
        <model.version.123>1.2.3</model.version.123>
        <linlan.ocr.version>1.0.2</linlan.ocr.version>


    </properties>
    <url>https://gitee.com/linlannet/java-rapidocr-parent/tree/master/stage-rapidoc-server</url>
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <scm>
        <url>https://gitee.com/linlannet/java-rapidocr-parent/tree/master/stage-rapidoc-server</url>
        <connection>https://gitee.com/linlannet/java-rapidocr-parent/tree/master/stage-rapidoc-server</connection>
    </scm>
    <developers>
        <developer>
            <id>linlan</id>
            <name>linlan info</name>
            <email>linlannet@163.com</email>
            <organization>Linlan Corporation</organization>
            <url>https://gitee.com/linlaninfo</url>
            <roles>
                <role>Member</role>
            </roles>
            <timezone>Asia/Beijing</timezone>
        </developer>
    </developers>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>${spring.boot.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <version>${spring.boot.version}</version>
        </dependency>
        <!-- SpringSecurity的依赖配置-->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-bom</artifactId>
            <version>${spring-security.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <!-- redis 缓存操作 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
            <version>${spring.boot.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <!-- 配置文件加密 -->
        <dependency>
            <groupId>com.github.ulisesbocchio</groupId>
            <artifactId>jasypt-spring-boot</artifactId>
            <version>3.0.3</version>
        </dependency>

        <dependency>
            <groupId>net.linlan.tools</groupId>
            <artifactId>rapidocr</artifactId>
            <version>${linlan.ocr.version}</version>
        </dependency>
        <dependency>
            <groupId>net.linlan.tools</groupId>
            <artifactId>rapidocr-onnx-platform</artifactId>
            <version>${linlan.ocr.version}</version>
        </dependency>

        <dependency>
            <groupId>net.linlan.commons</groupId>
            <artifactId>commons-core</artifactId>
            <version>${linlan.tools.version}</version>
        </dependency>

    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/application*.yml</include>
                    <include>**/application*.yaml</include>
                    <include>**/application*.properties</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>**/application*.yml</exclude>
                    <exclude>**/application*.yaml</exclude>
                    <exclude>**/application*.properties</exclude>
                </excludes>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compile.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <!-- 生成源代码包 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${maven.source.version}</version>
                <executions>
                    <!-- 第一次执行 -->
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                        <phase>package</phase>
                        <!-- 不指定分类器，生成默认的源代码 JAR 文件 -->
                    </execution>
                    <!-- 第二次执行 -->
                    <execution>
                        <id>attach-additional-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                        <phase>package</phase>
                        <!-- 为第二次执行配置分类器 -->
                        <configuration>
                            <classifier>additional</classifier>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- 生成Java文档包 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven.javadoc.version}</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- 由于如下启用造成deploy上传文件较大，暂时注释。生成独立运行jar包，放开如下的注释即可 -->
<!--            <plugin>-->
<!--                <groupId>org.springframework.boot</groupId>-->
<!--                <artifactId>spring-boot-maven-plugin</artifactId>-->
<!--                <version>${spring.boot.version}</version>-->
<!--                <configuration>-->
<!--                    <includeSystemScope>true</includeSystemScope>-->
<!--                    <mainClass>net.linlan.stage.EntApplication</mainClass>-->
<!--                </configuration>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <goals>-->
<!--                            <goal>repackage</goal>-->
<!--                        </goals>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
            <!-- GPG 签名插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>${maven.gpg.version}</version>
                <executions>
                    <execution>
                        <!-- 绑定到 verify 阶段自动签名 -->
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <keyname>0EC989C27692C7D4</keyname>
                    <!-- 可选配置项 -->
                    <gpgArguments>
                        <arg>--pinentry-mode</arg>
                        <arg>loopback</arg> <!-- 解决无终端环境下的密码输入问题 -->
                    </gpgArguments>
                </configuration>
            </plugin>
            <!-- 新版本 发布到 https://central.sonatype.org/ 需要采用如下插件 -->
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <version>${maven.sonatype.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <publishingServerId>sonatype-central</publishingServerId>
                    <autoPublish>true</autoPublish>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <!--
    打包命令：mvn clean package -P linux-x86_64 -Dlinux-build 加载支持linux架构x86_64的so库
    打包命令：mvn clean package -P linux-arm64 -Dlinux-build 加载支持linux架构arm64的so库
     -->
    <profiles>
        <profile>
            <id>linux-x86_64</id>
            <activation>
                <os>
                    <family>unix</family>
                    <arch>amd64</arch>
                </os>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>net.linlan.tools</groupId>
                    <artifactId>rapidocr-onnx-linux-x86_64</artifactId>
                    <version>${model.version.122}</version>
                </dependency>
                <dependency>
                    <groupId>net.linlan.tools</groupId>
                    <artifactId>rapidocr-ncnn-linux-x86_64</artifactId>
                    <version>${model.version.112}</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>linux-arm64</id>
            <activation>
                <os>
                    <family>unix</family>
                    <arch>arm64</arch>
                </os>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>net.linlan.tools</groupId>
                    <artifactId>rapidocr-onnx-linux-arm64</artifactId>
                    <version>${model.version.123}</version>
                </dependency>
                <dependency>
                    <groupId>net.linlan.tools</groupId>
                    <artifactId>rapidocr-ncnn-linux-arm64</artifactId>
                    <version>${model.version.123}</version>
                </dependency>
            </dependencies>
        </profile>
    </profiles>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.linlan.tools</groupId>
                <artifactId>rapidocr</artifactId>
                <version>${linlan.ocr.version}</version>
            </dependency>
            <dependency>
                <groupId>net.linlan.tools</groupId>
                <artifactId>rapidocr-ncnn-platform</artifactId>
                <version>${linlan.ocr.version}</version>
            </dependency>
            <dependency>
                <groupId>net.linlan.tools</groupId>
                <artifactId>rapidocr-onnx-platform</artifactId>
                <version>${linlan.ocr.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!-- 配置发布仓库 -->
    <distributionManagement>
        <snapshotRepository>
            <id>sonatype-central</id>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
        </snapshotRepository>
        <repository>
            <id>sonatype-central</id>
            <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
    </distributionManagement>

</project>
